### ISSUE TITLE
Is the corpus available?

### ISSUE THREAD

**Issue by nreimers** [facebookresearch/Sphere#5]
Thanks for compiling this great resource.

I saw that the sparse & dense index can be downloaded. I was wondering if the raw documents & paragraphs are also available somewhere?

**Comment by ola13** [comment]
Hi @nreimers, the corpus is not available to download directly, however it can be recreated relatively easily by doing a full index traversal - this won't yield full documents, but it will return the 100-token paragraphs along with document titles. I might consider adding a script to do that in the near future

**Comment by nreimers** [comment]
Hi @ola13 
Thanks for your quick response.

The raw document paragraphs are part of the sparse pyserini index? A script or a short hint on how to access all paragraphs would be really cool :)

**Comment by ola13** [comment]
They are part of the dense index metadata, I'll try to work on that in the upcoming weeks, but feel free to send a PR if you get there earlier! :)

**Comment by nreimers** [comment]
That would be great, thanks :)

**Comment by bobvanluijt** [comment]
Hi @ola13 –

I'm also interested in traversing through the indices if possible.

A quick hint of how we can iterate over the indices using Pyserini would be appreciated. I've already connected the index files (this was pretty straightforward), but it's unclear how to iterate over them.

PS:
More than happy to contribute back in any way, shape, or form how people can do this btw, just need a tiny bit of help understanding how the index is constructed :-)

**Comment by ola13** [comment]
Hi there, I'm not prioritising it right now, but the way I'd go around retrieving corpus data would be via the dense index - the title and text of passages forms metadata there, so using faiss to do a full index traversal should yield the original corpus. I haven't tried it before, but I highly suspect it's doable :)

I have less of an intuition about how and if that could be done in Pyserini

**Comment by bobvanluijt** [comment]
Thanks @ola13 – I'll dig into it 👍

**Comment by bobvanluijt** [comment]
@ola13 – almost there, we have two short questions, hopefully, you can help.

Am I correct that:

1. This is the model used: [facebook-dpr-ctx_encoder-single-nq-base](https://huggingface.co/facebook/dpr-ctx_encoder-single-nq-base)? Or is it another one (@CShorten can you please provide some more context about what you've been able to get from the article?)
2. A vector representation with the above model can be made of the `raw` sparse data, but the `raw` field is truncated at 100-tokens so the vector embedding will not create a 100% match (i.e., a dot-product distance of `0`)?

**Comment by CShorten** [comment]
Hey all, I see in - "Multi-Task Retrieval for Knowledge-Intensive Tasks" it is mentioned that "We provide a pre-trained snapshot of our best performing model, in the form of a BERT checkpoint.", but I am not sure where to find the checkpoints in https://github.com/facebookresearch/DPR.

It seemed like Hydra was telling me to look here - https://github.com/facebookresearch/DPR/blob/main/conf/encoder/hf_bert.yaml. But I don't see how I would point to other DPR model weights from here?

It would be nice if we could get some clarification on this as well, https://github.com/facebookresearch/DPR/issues/207.

Thank you!

**Comment by ola13** [comment]
Hi @CShorten, thanks for your questions - they seem to belong in the DPR repository though.

To give ou some pointers, you might have more luck browsing the multi-task specific branch in the DPR repo - https://github.com/facebookresearch/DPR/tree/multi_task_training

Re checkpoint conversions, using `strict= False` should help like the issue states, but again I'd seek more help either in DPR or transformers repositories.

**Comment by bobvanluijt** [comment]
It's live, both JSONL and Spark, can be imported directly into Weaviate: https://weaviate.io/blog/2022/12/sphere-dataset-in-weaviate.html
