### ISSUE TITLE
standalone client access?

### ISSUE THREAD

**Issue by fredzannarbor** [facebookresearch/Sphere#6]
Hi,

Is the standalone client meant to be able to access an external server without installing any data on my PC?

python scripts/sphere_client_demo_hf.py \
    --encoder checkpoints/dpr_web_query_encoder_hf \
    --discovery-config faiss_index/disovery_config.txt \
    --index-id dense
    
 I do not have ready access to a system that can accommodate the ~1TB indices.

**Comment by ola13** [comment]
Hi @fredzannarbor, unfortunately, we're not currently hosting the server anywhere, but I agree having a service like that running would be a great asset.
